FTP-1380: Creation of Icon component, type and story.
axelerant-trainings-frontend/grocery-plus pull request #24
Opened 2022-09-30 04:57 UTC by subhasishnathAxelerant

![1380-pr](https://user-images.githubusercontent.com/89250176/194574403-226f166b-4edf-4268-9a55-650eb54070e0.png)

<img width="1440" alt="Screenshot 2022-09-30 at 10 24 23 AM" src="https://user-images.githubusercontent.com/89250176/193193291-8dd009d2-6f88-4011-bb5d-26e3831d662e.png">

https://axelerant.atlassian.net/browse/FTP-1380

2022-10-06 07:05 UTC, subhasishnathAxelerant commented
Lint is failing on pull. Which is fixed in https://github.com/axelerant-trainings-frontend/grocery-plus/pull/30 by Tushar.

2022-10-07 05:22 UTC, skippednote requested changes

2022-10-07 05:22 UTC, skippednote commented on components/Icon/Icon.test.tsx
> +      'M8.19785 10.655V15.655C8.19785 16.205 7.74785 16.655 7.19785 16.655H3.19785C2.64785 16.655 2.19785 16.205 2.19785 15.655V8.655H0.497852C0.037852 8.655 -0.172148 8.085 0.167852 7.785L8.52785 0.
Please group all the tests in a single describe block

2022-10-07 05:22 UTC, skippednote commented on components/Icon/Icon.test.tsx
> +describe('Test Icon component', () => {
```suggestion
describe('Icon', () => {
```

2022-10-07 05:22 UTC, skippednote commented on @types/Icon.types.ts
> +  className: string;
```suggestion
  className: 'charcoal' | 'white';
```

2022-10-07 05:22 UTC, skippednote commented on components/Icon/Icon.tsx
> +const Icon: React.FC<iconType> = ({ icon, width, height, className = '' }) => {
```suggestion
const Icon: React.FC<iconType> = ({ icon, width, height, variant }) => {
```

2022-10-07 05:22 UTC, skippednote commented on components/Icon/Icon.tsx
> +      className={`icon w-fit h-auto ${className}`}
```suggestion
      className={`icon w-fit h-auto text-${variant}`}
```

2022-10-07 05:22 UTC, skippednote commented on components/Icon/Icon.tsx
> +        <path d={icon} fill="currentcolor" data-testid="svgIconPath" />
use hyphen instead of lowerCamelCase

2022-10-07 05:22 UTC, skippednote commented on components/Icon/Icon.tsx
> +        data-testid="svgIcon"
use hyphen instead of lowerCamelCase

2022-10-07 07:12 UTC, subhasishnathAxelerant commented on components/Icon/Icon.test.tsx
> +describe('Test Icon component', () => {
Done.

2022-10-07 07:19 UTC, subhasishnathAxelerant commented on @types/Icon.types.ts
> +  className: string;
Done.

2022-10-07 07:20 UTC, subhasishnathAxelerant commented on components/Icon/Icon.test.tsx
> +      'M8.19785 10.655V15.655C8.19785 16.205 7.74785 16.655 7.19785 16.655H3.19785C2.64785 16.655 2.19785 16.205 2.19785 15.655V8.655H0.497852C0.037852 8.655 -0.172148 8.085 0.167852 7.785L8.52785 0.
Done.

2022-10-07 07:25 UTC, subhasishnathAxelerant commented on @types/Icon.types.ts
> +  className: string;
Done.

2022-10-07 07:37 UTC, subhasishnathAxelerant commented on components/Icon/Icon.tsx
> +      className={`icon w-fit h-auto ${className}`}
Changed to:
`className={`icon w-fit h-auto text-${variant} ${extraClasses ? extraClasses : ""}`}`

2022-10-07 08:02 UTC, subhasishnathAxelerant commented on components/Icon/Icon.tsx
> +        data-testid="svgIcon"
Done.

2022-10-07 08:02 UTC, subhasishnathAxelerant commented on components/Icon/Icon.tsx
> +        <path d={icon} fill="currentcolor" data-testid="svgIconPath" />
Done

2022-10-10 05:05 UTC, skippednote approved these changes

2022-10-10 05:05 UTC, merged