FTP-1379: Design System Tokens: Scales added.
axelerant-trainings-frontend/grocery-plus pull request #25
Opened 2022-09-30 12:58 UTC by subhasishnathAxelerant

https://axelerant.atlassian.net/browse/FTP-1379

2022-10-07 02:52 UTC, subhasishnathAxelerant commented
Lint is failing onpush and pull. Which is fixed in https://github.com/axelerant-trainings-frontend/grocery-plus/pull/30 by Tushar.
CC: @skippednote

2022-10-07 05:40 UTC, skippednote requested changes

2022-10-07 05:40 UTC, skippednote commented on tailwind.config.js
>          '2xl': '1214px',
Group all these together under spacing
Replace names with numbers (sm, lg, xl, etc).

2022-10-10 04:13 UTC, subhasishnathAxelerant commented on tailwind.config.js
>          '2xl': '1214px',
Done.

2022-10-10 05:06 UTC, skippednote commented
@subhasishnathAxelerant Please rebase

2022-10-10 05:52 UTC, merged