FTP-1383:Design-systems-components-buttons
axelerant-trainings-frontend/grocery-plus pull request #26
Opened 2022-10-03 06:54 UTC by tushar8184

<img width="1335" alt="Screenshot 2022-10-03 at 12 23 21 PM" src="https://user-images.githubusercontent.com/89643385/193517306-751a007f-4035-49bc-8470-4a704cac7a5c.png">

2022-10-07 05:42 UTC, skippednote commented on components/button/Button.test.tsx
>  import { render, screen } from '@testing-library/react';
Please revert this file

2022-10-07 05:46 UTC, skippednote requested changes

2022-10-07 05:46 UTC, skippednote commented on components/button/Button.test.tsx
>    });
Add more tests to check all variants and other props

2022-10-07 05:46 UTC, skippednote commented on components/button/Button.tsx
> +  text = '',
let's use children instead

2022-10-07 05:46 UTC, skippednote commented on components/button/Button.tsx
> +  text = '',
Text shouldn't have a default value

2022-10-07 05:46 UTC, skippednote commented on components/button/Button.tsx
> +    </div>
Let's use the Icon component here

2022-10-07 05:46 UTC, skippednote commented on @types/button.types.ts
> +  variant: string;
Use the values instead.

2022-10-07 06:54 UTC, tushar8184 commented on components/button/Button.test.tsx
>  import { render, screen } from '@testing-library/react';
Made the required changes

2022-10-07 07:11 UTC, tushar8184 commented on components/button/Button.tsx
> +  text = '',
Done

2022-10-07 07:12 UTC, tushar8184 commented on components/button/Button.tsx
> +  text = '',
Done

2022-10-07 07:25 UTC, tushar8184 commented on components/button/Button.test.tsx
>    });
Have added one more test to check all the variants.

2022-10-07 07:26 UTC, tushar8184 commented on @types/button.types.ts
> +  variant: string;
Done

2022-10-10 05:10 UTC, skippednote requested changes

2022-10-10 05:10 UTC, skippednote commented on components/button/Button.test.tsx
> +  });
Please add the variant name in the `it` string

2022-10-10 05:10 UTC, skippednote commented on @types/button.types.ts
> +  variant: string;
You need to list all the variant names here instead of `string`

2022-10-10 05:10 UTC, skippednote commented on components/button/Button.test.tsx
>    });
We need to add a test for `onClick`

2022-10-12 05:28 UTC, skippednote commented
Please remove the icons in this pr

2022-10-12 05:28 UTC, skippednote requested changes

2022-10-12 05:28 UTC, skippednote commented on components/button/Button.test.tsx
> +
Can we move this test to the bottom

2022-10-12 05:28 UTC, skippednote commented on components/button/Button.test.tsx
> +  it('display an alert onClick', () => {
```suggestion
  it('add class on onClick', () => {
```

2022-10-12 05:28 UTC, skippednote commented on components/button/Button.tsx
> +  let classes = '';
```suggestion
  let classes = defaultClasses';
```

2022-10-12 05:28 UTC, skippednote commented on components/button/Button.tsx
> +    classes = `${defaultClasses} bg-green-primary h-12`;
```suggestion
    classes += ` bg-green-primary h-12`;
```

2022-10-12 06:27 UTC, tushar8184 commented on components/button/Button.test.tsx
> +
move to the bottom

2022-10-12 06:28 UTC, tushar8184 commented on components/button/Button.test.tsx
> +  it('display an alert onClick', () => {
added 'add class on'

2022-10-13 04:44 UTC, merged