FTP-1381:form-fields
axelerant-trainings-frontend/grocery-plus pull request #27
Opened 2022-10-03 08:38 UTC by HamidAli111

<img width="1503" alt="Screenshot 2022-10-03 at 1 58 12 PM" src="https://user-images.githubusercontent.com/95576134/193535177-4a6df70f-61ca-4996-8aac-146eb0e858a9.png">
<img width="1067" alt="Screenshot 2022-10-03 at 1 58 19 PM" src="https://user-images.githubusercontent.com/95576134/193535199-bf553a2a-5adf-47ae-ab61-896d98701c2e.png">
<img width="986" alt="Screenshot 2022-10-03 at 1 58 42 PM" src="https://user-images.githubusercontent.com/95576134/193535206-b5564e6d-b8f8-4d2a-9563-a2410c0c196f.png">
<img width="1073" alt="Screenshot 2022-10-03 at 1 58 48 PM" src="https://user-images.githubusercontent.com/95576134/193535215-cb7c2945-12c8-495a-92f9-be9996e53660.png">
<img width="481" alt="Screenshot 2022-10-03 at 1 58 52 PM" src="https://user-images.githubusercontent.com/95576134/193535219-ae1bcf09-85d3-4ef5-b212-6301238f5ad1.png">
<img width="1007" alt="Screenshot 2022-10-03 at 1 58 59 PM" src="https://user-images.githubusercontent.com/95576134/193535224-1280beaa-863d-444b-ac6b-07480644301c.png">
<img width="889" alt="Screenshot 2022-10-06 at 4 56 31 PM" src="https://user-images.githubusercontent.com/95576134/194301146-10299a06-381a-4900-bac4-2a0d1abe8860.png">

<img width="921" alt="Screenshot 2022-10-03 at 2 03 01 PM" src="https://user-images.githubusercontent.com/95576134/193535232-baf96ad6-0ac2-4823-88bb-e22d82656201.png">

2022-10-10 05:26 UTC, skippednote commented
Replace `.spec.ts` with `.test.ts`
Replace `.png` with Icon component

2022-10-10 05:26 UTC, skippednote requested changes

2022-10-10 05:26 UTC, skippednote commented on components/button/Tag.spec.tsx
> +import Tag from './Tag';
Let's name it time

2022-10-10 05:26 UTC, skippednote commented on @types/Searchbox.ts
> +type searchboxType = {
Let's aggregate all form-related types in a `form.types.ts` file

2022-10-10 05:26 UTC, skippednote commented on components/inputField/InputField.tsx
> +  let inpType = '';
let's write the whole thing

2022-10-10 05:26 UTC, skippednote commented on components/inputField/InputField.tsx
> +          <h1 className={extraClasses}>{label}</h1>
This should be a label

2022-10-10 05:26 UTC, skippednote commented on components/inputField/InputField.tsx
> +  const extraClasses = 'pl-[61px] absolute text-sm mt-1.5';
This should be renamed to `labelClasses`

2022-10-10 06:09 UTC, HamidAli111 commented on @types/Searchbox.ts
> +type searchboxType = {
As there were some styling issues is the reason we have to keep it as separate from the inputfields

2022-10-10 07:12 UTC, HamidAli111 commented on components/button/Tag.spec.tsx
> +import Tag from './Tag';
Made the required changes

2022-10-10 07:14 UTC, HamidAli111 commented on components/inputField/InputField.tsx
> +  let inpType = '';
Made the required chnages

2022-10-10 07:14 UTC, HamidAli111 commented on components/inputField/InputField.tsx
> +          <h1 className={extraClasses}>{label}</h1>
Made the required chnages

2022-10-10 07:14 UTC, HamidAli111 commented on components/inputField/InputField.tsx
> +  const extraClasses = 'pl-[61px] absolute text-sm mt-1.5';
Made the required chnages

2022-10-11 05:29 UTC, skippednote requested changes

2022-10-11 05:29 UTC, skippednote commented on pages/testing.tsx
> +import React from 'react';
Please remove

2022-10-11 05:29 UTC, skippednote commented on pages/testing.tsx
> +export default Testing;
Remove all the png icons.

2022-10-11 05:29 UTC, skippednote commented on components/inputField/Searchbox.tsx
> +        data-testid="box"
let's use a more verbose name instead of `box`

2022-10-11 05:29 UTC, skippednote commented on components/inputField/Searchbox.stories.tsx
> +  icon: '/icons/search_24px.png',
Can we remove this?

2022-10-11 07:05 UTC, HamidAli111 commented on pages/testing.tsx
> +export default Testing;
Made the required chnages

2022-10-11 07:05 UTC, HamidAli111 commented on pages/testing.tsx
> +import React from 'react';
Made the required chnages

2022-10-11 07:05 UTC, HamidAli111 commented on components/inputField/Searchbox.tsx
> +        data-testid="box"
Made the required chnages

2022-10-11 07:05 UTC, HamidAli111 commented on components/inputField/Searchbox.stories.tsx
> +  icon: '/icons/search_24px.png',
Made the required chnages

2022-10-13 04:57 UTC, skippednote approved these changes

2022-10-13 04:57 UTC, skippednote commented on components/time/Time.test.tsx
> +    const EndTime = '10AM';
const should either be upper case or camelCase, not capitalcase

2022-10-13 04:57 UTC, skippednote commented on components/time/Time.test.tsx
> +    const EndTime = '10AM';
const should either be upper case or camelCase, not capitalcase

2022-10-13 05:04 UTC, merged