FTP-1377-typography-tests
axelerant-trainings-frontend/grocery-plus pull request #33
Opened 2022-10-07 06:06 UTC by HamidAli111

updated

2022-10-10 05:52 UTC, skippednote requested changes

2022-10-10 05:52 UTC, skippednote commented on components/heading/Heading.spec.tsx
> +  });
Please make the `it` string verbose

2022-10-10 06:06 UTC, HamidAli111 commented on components/heading/Heading.spec.tsx
> +  });
@skippednote Made the required changes and also changed .spec to .test

2022-10-11 05:52 UTC, skippednote requested changes

2022-10-11 05:52 UTC, skippednote commented on components/text/Text.tsx
> +  return <h2 className={classes + ' ' + extraClasses}>{title}</h2>;
Let's make this a `p`

2022-10-11 05:52 UTC, skippednote commented on components/text/Text.tsx
> +    classes = 'font-bold text-2xl leading-xl xlarge-bold';
Let's remove the additional classes

2022-10-11 06:32 UTC, HamidAli111 commented on components/heading/Heading.spec.tsx
> +  });
@skippednote Made the required changes

2022-10-11 06:32 UTC, HamidAli111 commented on components/text/Text.tsx
> +  return <h2 className={classes + ' ' + extraClasses}>{title}</h2>;
@skippednote Made the required changes

2022-10-11 06:33 UTC, HamidAli111 commented on components/text/Text.tsx
> +    classes = 'font-bold text-2xl leading-xl xlarge-bold';
@skippednote Made the required changes

2022-10-12 07:10 UTC, HamidAli111 commented on components/text/Text.tsx
> +    classes = 'font-bold text-2xl leading-xl xlarge-bold';
Hey @skippednote Not able to see the feedback you gave over the DSM

2022-10-13 05:15 UTC, skippednote requested changes

2022-10-13 05:15 UTC, skippednote commented on components/heading/Heading.tsx
> +  return <h1 className={classes + ' ' + extraClasses}>{title}</h1>;
```suggestion
  const Tag = `h${size}` as keyof JSX.IntrinsicElements;
  return <Tag className={classes + ' ' + extraClasses}>{title}</Tag>;
```

2022-10-13 05:36 UTC, HamidAli111 commented on components/heading/Heading.tsx
> +  return <h1 className={classes + ' ' + extraClasses}>{title}</h1>;
@skippednote While making the changes I find out that sizes we are already changing text sizes based on the variant, do we still need to implement this way?

2022-10-13 07:07 UTC, HamidAli111 commented on components/heading/Heading.tsx
> +  return <h1 className={classes + ' ' + extraClasses}>{title}</h1>;
@skippednote Made the required changes

2022-10-14 04:53 UTC, merged